- name: Set Hostname
  hostname:
    name: "{{machine_name}}"

- name: Copy hosts file
  template:
    src: hosts
    dest: /etc/hosts

- name: Install Minimal Set of Packages
  apt:
    name:
      - unattended-upgrades
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - man-db
      - htop
      - net-tools
      - dnsutils
      - netcat
      - python3
      - git
      - build-essential
      - vim
      - kitty-terminfo
    update_cache: yes
