- name: Create admin group
  group:
    name: sudo

- name: Add admin group members to sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: "%sudo ALL"
    line: "%sudo ALL=(ALL:ALL) NOPASSWD:ALL"

- name: Create users
  user:
    name: "{{item.name}}"
    shell: "{{ item.shell | default('/usr/bin/bash') }}"
    state: "{{ item.state | default('present') }}"
    groups:
      - sudo
    append: yes
  with_items: "{{admin_users}}"

- name: Copy configuration for admins
  copy:
    src: "admin-users/{{item.name}}/"
    dest: "/home/{{item.name}}/"
    owner: "{{item.name}}"
    group: "{{item.name}}"
    mode: u=rw,o=,g=
    force: no
  when: item.state is undefined or item.state != 'absent'
  with_items: "{{admin_users}}"

- name: Delete admin users passwords
  user:
    name: "{{item.name}}"
    password: '!'
  when: item.state is undefined or item.state != 'absent'
  with_items: "{{admin_users}}"

- name: Delete root password
  user:
    name: root
    password: '!'

- name: Disable SSH password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "#?PasswordAuthentication"
    line: "PasswordAuthentication no"
