- name: Add Bullseye repository
  apt_repository:
    repo: "deb {{bullseye_mirror}} bullseye main"
    state: present

- name: Install Python and Certbot from Bullseye
  apt:
    name:
      - python3.9
      - virtualenv
      - certbot
      - python3-certbot-nginx
    install_recommends: no
    update_cache: yes
    default_release: bullseye
    autoremove: yes
