- name: Create Gunicorn user
  user:
    name: gunicorn
    system: yes
    create_home: yes

- name: Create Django database
  postgresql_db:
    name: "{{django_database_name}}"
  become: yes
  become_user: postgres

- name: Create Django database user
  postgresql_user:
    name: "{{django_database_user}}"
    password: "{{django_database_password}}"
    db: "{{django_database_name}}"
  become: yes
  become_user: postgres

- name: Create Django settings directory
  file:
    path: /etc/tournesol
    state: directory

- name: Copy Django settings
  template:
    src: settings.yaml.j2
    dest: /etc/tournesol/settings.yaml
  notify: Restart Gunicorn

- name: Copy Django OIDC RSA private key
  template:
    src: django_oidc_rsa_private_key.j2
    dest: /root/django_oidc_rsa_private_key
    mode: u=rw,g=,o=
  notify:
    - Write Swagger UI OAuth client ID into root's home
    - Write Swagger UI OAuth client secret into root's home
    - Create Swagger UI OAuth application in Django database

- name: Create Django application directory
  file:
    path: /srv/tournesol-backend
    state: directory
    owner: gunicorn
    group: gunicorn

- name: Create remote_tmp directory for Gunicorn user
  file:
    path: /home/gunicorn/.ansible/tmp
    state: directory
    owner: gunicorn
    group: gunicorn

- name: Clone Django application repository
  git:
    repo: https://github.com/tournesol-app/tournesol-backend.git
    dest: /srv/tournesol-backend
    version: "{{backend_target_branch}}"
    force: yes
  become: yes
  become_user: gunicorn
  notify:
    - Migrate Django database
    - Collect Django static assets
    - Restart Gunicorn

- name: Create Virtualenv for Django project
  pip:
    name:
      - gunicorn
      - uvicorn
    virtualenv: /srv/tournesol-backend/venv
    virtualenv_python: python3.9
  become: yes
  become_user: gunicorn
  notify: Restart Gunicorn

- name: Install requirements for Django project
  pip:
    requirements: /srv/tournesol-backend/requirements.txt
    virtualenv: /srv/tournesol-backend/venv
    virtualenv_python: python3.9
  become: yes
  become_user: gunicorn
  notify: Restart Gunicorn

- name: Copy Gunicorn service file
  copy:
    src: gunicorn.service
    dest: /etc/systemd/system/gunicorn.service
  notify: Restart Gunicorn

- name: Copy Gunicorn socket file
  copy:
    src: gunicorn.socket
    dest: /etc/systemd/system/gunicorn.socket

- name: Create static assets directory
  file:
    path: /var/www/html/static
    owner: gunicorn
    group: gunicorn
    mode: u=rwx,g=rx,o=rx
    state: directory
  notify:
    - Collect Django static assets

- name: Enable and start Gunicorn
  systemd:
    name: gunicorn.socket
    enabled: true
    state: started
    daemon_reload: true

- name: Copy Nginx configuration
  template:
    src: tournesol.j2
    dest: /etc/nginx/sites-available/tournesol
  notify:
    - Reload Nginx

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/tournesol
    dest: /etc/nginx/sites-enabled/tournesol
    state: link
  notify: Reload Nginx

- meta: flush_handlers
