- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
    daemon_reload: true

- name: Restart MariaDB
  systemd:
    name: mariadb
    state: restarted
    daemon_reload: true

- name: Create Mediawiki alternative root
  file:
    path: /var/lib/mediawiki-w
    state: directory

- name: Link Mediawiki alternative root
  file:
    path: /var/lib/mediawiki-w/w
    src: /var/lib/mediawiki
    state: link

- name: Install Mediawiki
  command: |
    php /var/lib/mediawiki/maintenance/install.php \
    --confpath /tmp/LocalSettings.php \
    --dbname "{{mediawiki_database_name}}" \
    --dbuser "{{mediawiki_database_user}}" \
    --dbpass "{{mediawiki_database_password}}" \
    --installdbuser "{{mediawiki_database_user}}" \
    --installdbpass "{{mediawiki_database_password}}" \
    --pass "{{mediawiki_admin_password}}" \
    --server {{mediawiki_scheme}}://{{mediawiki_domain_name}} \
    --scriptpath /w \
    Tournesol \
    admin
  become: yes
  become_user: www-data

- name: Write Mediawiki database password into root's home
  shell: "echo \"{{mediawiki_database_password}}\" > /root/mediawiki_database_password && chmod go-rwx /root/mediawiki_database_password"

- name: Write Mediawiki admin password into root's home
  shell: "echo \"{{mediawiki_admin_password}}\" > /root/mediawiki_admin_password && chmod go-rwx /root/mediawiki_admin_password"

- name: Write Mediawiki secret key into root's home
  shell: "echo \"{{mediawiki_secret_key}}\" > /root/mediawiki_secret_key && chmod go-rwx /root/mediawiki_secret_key"

- name: Write Mediawiki OIDC client ID into root's home
  shell: "echo \"{{mediawiki_oidc_client_id}}\" > /root/mediawiki_oidc_client_id && chmod go-rwx /root/mediawiki_oidc_client_id"

- name: Write Mediawiki OIDC client secret into root's home
  shell: "echo \"{{mediawiki_oidc_client_secret}}\" > /root/mediawiki_oidc_client_secret && chmod go-rwx /root/mediawiki_oidc_client_secret"

- name: Create OIDC application in Django database
  shell: 
    cmd: now=$(date -I) && psql -d tournesol <<< "insert into oauth2_provider_application (client_id, redirect_uris, client_type, authorization_grant_type, client_secret, name, skip_authorization, algorithm, created, updated) values ('{{mediawiki_oidc_client_id}}', '{{mediawiki_scheme}}://{{mediawiki_domain_name}}/wiki/Special:PluggableAuthLogin', 'confidential', 'authorization-code', '{{mediawiki_oidc_client_secret}}','MediaWiki', true, 'RS256', '$now', '$now');"
    executable: /usr/bin/bash
  become: yes
  become_user: postgres

- name: Run Composer
  command:
    cmd: "composer update"
    chdir: /var/lib/mediawiki
  # become: yes
  # become_user: www-data

- name: Update Mediawiki database
  command: "php /var/lib/mediawiki/maintenance/update.php"
  become: yes
  become_user: www-data
