- name: Install Nftables
  apt:
    name: nftables
    update_cache: true

- name: Copy Nftables configuration file
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
  notify: Reload Nftables

- name: Ensure Nftables is enabled and running
  systemd:
    name: nftables
    state: started
    enabled: true
    daemon_reload: true

- meta: flush_handlers
