all:
  children:
    tournesol:
      hosts:
        tournesol-vm:
          ansible_host: "192.168.122.56"
          machine_name: "tournesol"
          # ansible_user: "jst"
          django_debug: "True"
          django_main_url: "http://{{ansible_host}}/"
          django_database_name: "tournesol"
          django_database_user: "tournesol"
        tournesol-staging:
          ansible_host: "tournesol.technocracy.dev"
          machine_name: "tournesol"
          # ansible_user: "jst"
          django_debug: "True"
          django_main_url: "http://{{ansible_host}}/"
          django_database_name: "tournesol"
          django_database_user: "tournesol"
          domain_name: "tournesol.technocracy.dev"
          letsencrypt_email: "jst@kleis.ch"

      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pipelining: true
