all:
  children:
    tournesol:
      hosts:
        # VM for local development
        tournesol-vm:
          ansible_host: tournesol-vm
          machine_name: tournesol
          # ansible_user: jst
          domain_name: tournesol-vm
          api_domain_name: tournesol-api

          bullseye_mirror: http://debian.ethz.ch/debian/

          django_debug: "True"
          django_main_url: "http://{{api_domain_name}}"
          django_database_name: tournesol
          django_database_user: tournesol

          backend_target_branch: dev-env
          loki_version: "v2.2.1"
          frontend_target_branch: password-login-flow
          nvm_version: "v0.38.0"
          npm_lts_version: fermium

          mediawiki_domain_name: tournesol-wiki
          mediawiki_scheme: http
          mediawiki_database_name: mediawiki
          mediawiki_database_user: mediawiki

        # Staging Vultr VM
        tournesol-staging:
          ansible_host: staging.tournesol.app
          machine_name: tournesol
          # ansible_user: jst
          domain_name: staging.tournesol.app
          api_domain_name: "api.{{domain_name}}"

          bullseye_mirror: http://debian.ethz.ch/debian/

          django_debug: "True"
          django_main_url: https://{{api_domain_name}}
          django_database_name: tournesol
          django_database_user: tournesol

          backend_target_branch: hardcoded-ip-in-README
          loki_version: "v2.2.1"
          frontend_target_branch: npm-version-update
          nvm_version: "v0.38.0"
          npm_lts_version: fermium

          # Setting this triggers TLS configuration
          letsencrypt_email: tournesol.application@gmail.com

          mediawiki_domain_name: "wiki.{{domain_name}}"
          mediawiki_scheme: https
          mediawiki_database_name: mediawiki
          mediawiki_database_user: mediawiki

      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pipelining: true
