all:
  children:
    tournesol:
      hosts:

        # VM for local development
        tournesol-vm:
          ansible_host: tournesol-vm
          machine_name: tournesol
          # ansible_user: jst
          domain_name: tournesol-vm

          bullseye_mirror: http://debian.ethz.ch/debian/

          django_debug: "True"
          django_main_url: "http://{{domain_name}}/"
          django_prefix_uri: "api/"
          django_database_name: tournesol
          django_database_user: tournesol

          backend_target_branch: serve-on-prefix
          loki_version: "v2.2.1"
          frontend_target_branch: npm-version-update
          nvm_version: "v0.38.0"
          npm_lts_version: fermium

          mediawiki_domain_name: tournesol-wiki
          mediawiki_database_name: mediawiki
          mediawiki_database_user: mediawiki


        # Staging Vultr VM
        tournesol-staging:
          ansible_host: tournesol.technocracy.dev
          machine_name: tournesol
          # ansible_user: jst
          domain_name: tournesol.technocracy.dev

          bullseye_mirror: http://debian.ethz.ch/debian/

          django_debug: "True"
          django_main_url: https://{{domain_name}}/
          django_prefix_uri: api/
          django_database_name: tournesol
          django_database_user: tournesol

          backend_target_branch: serve-on-prefix
          loki_version: "v2.2.1"
          frontend_target_branch: npm-version-update
          nvm_version: "v0.38.0"
          npm_lts_version: fermium

          # Setting this triggers TLS configuration
          letsencrypt_email: jst@kleis.ch

          mediawiki_domain_name: "wiki.{{domain_name}}"
          mediawiki_database_name: mediawiki
          mediawiki_database_user: mediawiki


      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_pipelining: true
