name: Frontend lint and tests

on: [push, pull_request]

defaults:
  run:
    working-directory: frontend

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/fermium'
      - run: yarn
      - run: ./scripts/generate-services-from-openapi.sh
      - run: yarn test
